url: 
baseurl: 

# Site settings
title: Ipp Club
email: your-email@domain.com
description: "我们是一群萌萌的搬砖工，i++是我家，啦啦啦啦啦【擦，happy tree friends既视感】"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:

- name: JinGe
  pic: pigpigyyy.png
  position: Founder
  social:
    - title: github
      url: https://github.com/pigpigyyy


- name: jaredlee
  pic: jaredlee.jpg
  position: Lead Designer
  social:
    - title: github
      url: https://github.com/jaredlee/

- name: haeckel
  pic: haeckel.jpg
  position: Lead Developer
  social:
    - title: github
      url: https://github.com/haeckel/

- name: Huozhi
  pic: huozhi.png
  position: Code Manager
  social:
    - title: github
      url: https://github.com/lavende/

- name: NanGe
  pic: nange.jpg
  position: Designer
  social:
    - title: github
      url: https://github.com/pricklypearlsn


- name: bingbing
  pic: bingbing.png
  position: Developer
  social:
    - title: github
      url: https://github.com/695215742/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: laptop
    url: http://ippclub.github.io
  - title: github
    url: http://github.com/IppClub
  - title: start-o
    url: http://ippclub.org/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Nanjing Jiangsu, CHINA 211189

# Build settings
markdown: kramdown
permalink: pretty